name: Python Pytest

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  pytest:
    # Run on a Ubuntu VM
    runs-on: ubuntu-latest
    steps:
      # Checkout the GitHub repo
      - uses: actions/checkout@v2

      # Install Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}
      
      # Pip install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # Move into the project folder and run pytest
      - name: Test with pytest
        working-directory: .
        run: pytest -vv